metadata:
  existing_links:
  - corp_master_name_corp_presidents_name_fuzzy_match
  - corp_master_name_corp_master_name_fuzzy_match
  - corp_presidents_address_corp_presidents_address_unit_fuzzy_match
  - corp_presidents_address_corp_presidents_address_street_fuzzy_match
  - corp_presidents_name_corp_presidents_name_fuzzy_match
  - corp_presidents_name_corp_presidents_name_name_match
  - corp_master_name_corp_master_name_name_match
  - corp_master_name_corp_presidents_name_name_match
  - corp_presidents_address_llc_managers_address_unit_fuzzy_match
  - corp_presidents_address_llc_managers_address_street_fuzzy_match
  - corp_presidents_address_llc_master_address_unit_fuzzy_match
  - corp_presidents_address_llc_master_address_street_fuzzy_match
  - corp_master_name_llc_managers_name_fuzzy_match
  - corp_presidents_name_llc_managers_name_fuzzy_match
  - corp_master_name_llc_master_name_fuzzy_match
  - corp_presidents_name_llc_master_name_fuzzy_match
  - corp_presidents_name_llc_master_name_name_match
  - corp_master_name_llc_master_name_name_match
  - corp_presidents_name_llc_managers_name_name_match
  - corp_master_name_llc_managers_name_name_match
  - corp_presidents_address_llc_master_address_address_match
  - corp_presidents_address_llc_master_address_street_match
  - corp_presidents_address_llc_master_address_unit_match
  - corp_presidents_address_llc_master_address_street_num_match
  - corp_presidents_address_llc_managers_address_address_match
  - corp_presidents_address_llc_managers_address_street_match
  - corp_presidents_address_llc_managers_address_unit_match
  - corp_presidents_address_llc_managers_address_street_num_match
  - llc_managers_address_llc_master_address_unit_fuzzy_match
  - llc_managers_address_llc_master_address_street_fuzzy_match
  - llc_managers_name_llc_master_name_fuzzy_match
  - llc_managers_address_llc_managers_address_unit_fuzzy_match
  - llc_managers_address_llc_managers_address_street_fuzzy_match
  - llc_managers_name_llc_managers_name_fuzzy_match
  - llc_master_address_llc_master_address_unit_fuzzy_match
  - llc_master_address_llc_master_address_street_fuzzy_match
  - llc_master_name_llc_master_name_fuzzy_match
  - llc_master_name_llc_master_name_name_match
  - llc_master_address_llc_master_address_address_match
  - llc_master_address_llc_master_address_street_match
  - llc_master_address_llc_master_address_unit_match
  - llc_master_address_llc_master_address_street_num_match
  - llc_managers_name_llc_managers_name_name_match
  - llc_managers_address_llc_managers_address_address_match
  - llc_managers_address_llc_managers_address_street_match
  - llc_managers_address_llc_managers_address_unit_match
  - llc_managers_address_llc_managers_address_street_num_match
  - llc_managers_name_llc_master_name_name_match
  - llc_managers_address_llc_master_address_address_match
  - llc_managers_address_llc_master_address_street_match
  - llc_managers_address_llc_master_address_unit_match
  - llc_managers_address_llc_master_address_street_num_match
  - corp_presidents_address_parcel_parcel_mailing_address_unit_fuzzy_match
  - corp_presidents_address_parcel_parcel_mailing_address_street_fuzzy_match
  - corp_presidents_address_parcel_parcel_property_address_unit_fuzzy_match
  - corp_presidents_address_parcel_parcel_property_address_street_fuzzy_match
  - corp_master_name_parcel_parcel_tax_payer_name_fuzzy_match
  - corp_presidents_name_parcel_parcel_tax_payer_name_fuzzy_match
  - corp_presidents_name_parcel_parcel_tax_payer_name_name_match
  - corp_master_name_parcel_parcel_tax_payer_name_name_match
  - corp_presidents_address_parcel_parcel_property_address_address_match
  - corp_presidents_address_parcel_parcel_property_address_street_match
  - corp_presidents_address_parcel_parcel_property_address_unit_match
  - corp_presidents_address_parcel_parcel_property_address_street_num_match
  - corp_presidents_address_parcel_parcel_mailing_address_address_match
  - corp_presidents_address_parcel_parcel_mailing_address_street_match
  - corp_presidents_address_parcel_parcel_mailing_address_unit_match
  - corp_presidents_address_parcel_parcel_mailing_address_street_num_match
  - llc_managers_address_parcel_parcel_mailing_address_unit_fuzzy_match
  - llc_managers_address_parcel_parcel_mailing_address_street_fuzzy_match
  - llc_master_address_parcel_parcel_mailing_address_unit_fuzzy_match
  - llc_master_address_parcel_parcel_mailing_address_street_fuzzy_match
  - llc_managers_address_parcel_parcel_property_address_unit_fuzzy_match
  - llc_managers_address_parcel_parcel_property_address_street_fuzzy_match
  - llc_master_address_parcel_parcel_property_address_unit_fuzzy_match
  - llc_master_address_parcel_parcel_property_address_street_fuzzy_match
  - llc_managers_name_parcel_parcel_tax_payer_name_fuzzy_match
  - llc_master_name_parcel_parcel_tax_payer_name_fuzzy_match
  - llc_master_name_parcel_parcel_tax_payer_name_name_match
  - llc_managers_name_parcel_parcel_tax_payer_name_name_match
  - llc_master_address_parcel_parcel_property_address_address_match
  - llc_master_address_parcel_parcel_property_address_street_match
  - llc_master_address_parcel_parcel_property_address_unit_match
  - llc_master_address_parcel_parcel_property_address_street_num_match
  - llc_managers_address_parcel_parcel_property_address_address_match
  - llc_managers_address_parcel_parcel_property_address_street_match
  - llc_managers_address_parcel_parcel_property_address_unit_match
  - llc_managers_address_parcel_parcel_property_address_street_num_match
  - llc_master_address_parcel_parcel_mailing_address_address_match
  - llc_master_address_parcel_parcel_mailing_address_street_match
  - llc_master_address_parcel_parcel_mailing_address_unit_match
  - llc_master_address_parcel_parcel_mailing_address_street_num_match
  - llc_managers_address_parcel_parcel_mailing_address_address_match
  - llc_managers_address_parcel_parcel_mailing_address_street_match
  - llc_managers_address_parcel_parcel_mailing_address_unit_match
  - llc_managers_address_parcel_parcel_mailing_address_street_num_match
  - parcel_parcel_mailing_address_parcel_parcel_mailing_address_unit_fuzzy_match
  - parcel_parcel_mailing_address_parcel_parcel_mailing_address_street_fuzzy_match
  - parcel_parcel_tax_payer_name_parcel_parcel_tax_payer_name_fuzzy_match
  - parcel_parcel_tax_payer_name_parcel_parcel_tax_payer_name_name_match
  - parcel_parcel_property_address_parcel_parcel_property_address_address_match
  - parcel_parcel_property_address_parcel_parcel_property_address_street_match
  - parcel_parcel_property_address_parcel_parcel_property_address_unit_match
  - parcel_parcel_property_address_parcel_parcel_property_address_street_num_match
  - parcel_parcel_mailing_address_parcel_parcel_property_address_address_match
  - parcel_parcel_mailing_address_parcel_parcel_property_address_street_match
  - parcel_parcel_mailing_address_parcel_parcel_property_address_unit_match
  - parcel_parcel_mailing_address_parcel_parcel_property_address_street_num_match
  - parcel_parcel_mailing_address_parcel_parcel_mailing_address_address_match
  - parcel_parcel_mailing_address_parcel_parcel_mailing_address_street_match
  - parcel_parcel_mailing_address_parcel_parcel_mailing_address_unit_match
  - parcel_parcel_mailing_address_parcel_parcel_mailing_address_street_num_match
  last_updated: '2025-05-07 20:05:19'
options:
  bad_address_path: data/bad_addresses.csv
  db_path: db/linked_full.db
  export_tables: false
  force_db_create: true
  link_exclusions:
  - parcel_parcel_property_address_parcel_parcel_property_address_street_fuzzy_match
  - parcel_parcel_mailing_address_parcel_parcel_property_address_street_fuzzy_match
  - corp_presidents_address_corp_presidents_address_address_match
  - corp_presidents_address_corp_presidents_address_street_match
  - corp_presidents_address_corp_presidents_address_unit_match
  - corp_presidents_address_corp_presidents_address_street_num_match
  load_only: false
  probabilistic: true
  update_config_only: false
schemas:
- schema_name: parcel
  tables:
  - address_cols:
    - property_address
    - mailing_address
    address_cols_og:
    - property_address
    - mailing_address
    id_col: pin
    id_col_og: pin
    name_cols:
    - tax_payer_name
    name_cols_og:
    - tax_payer_name
    table_name: parcel
    table_name_path: data/parcel-addresses-foia-24-0230.parquet
- schema_name: llc
  tables:
  - address_cols:
    - address
    address_cols_og:
    - address
    id_col: file_num
    id_col_og: file_num
    name_cols:
    - name
    name_cols_og:
    - name
    table_name: master
    table_name_path: data/LLC_master_clnd.parquet
  - address_cols:
    - address
    address_cols_og:
    - address
    id_col: file_num
    id_col_og: file_num
    name_cols:
    - name
    name_cols_og:
    - name
    table_name: managers
    table_name_path: data/LLC_managers_clnd.parquet
- schema_name: corp
  tables:
  - address_cols:
    - address
    address_cols_og:
    - address
    id_col: file_num
    id_col_og: file_num
    name_cols:
    - name
    name_cols_og:
    - name
    table_name: presidents
    table_name_path: data/corp_presidents_clnd.parquet
  - address_cols: []
    address_cols_og: []
    id_col: file_num
    id_col_og: file_num
    name_cols:
    - name
    name_cols_og:
    - name
    table_name: master
    table_name_path: data/corp_master_clnd.parquet
