metadata:
  existing_links: []
  last_updated: '2025-04-21 15:34:18'
options:
  bad_address_path: data/bad_addresses.csv
  export_tables: false
  force_db_create: false
  link_exclusions:
  - parcel_parcel_property_address_parcel_parcel_property_address_street_fuzzy_match
  - parcel_parcel_mailing_address_parcel_parcel_property_address_street_fuzzy_match
  - corp_presidents_address_corp_presidents_address_address_match
  - corp_presidents_address_corp_presidents_address_street_match
  - corp_presidents_address_corp_presidents_address_unit_match
  - corp_presidents_address_corp_presidents_address_street_num_match
  probabilistic: true
  load_only: false
  update_config_only: false
schemas:
- schema_name: llc
  tables:
  - address_cols:
    - address
    address_cols_og:
    - address
    id_col: file_num
    id_col_og: file_num
    name_cols:
    - name_raw
    name_cols_og:
    - name_raw
    table_name: master
    table_name_path: data/LLC_master_clnd.parquet
  - address_cols:
    - address
    address_cols_og:
    - address
    id_col: file_num
    id_col_og: file_num
    name_cols:
    - name_raw
    name_cols_og:
    - name_raw
    table_name: managers
    table_name_path: data/LLC_managers_clnd.parquet
- schema_name: corp
  tables:
  - address_cols:
    - address
    address_cols_og:
    - address
    id_col: file_num
    id_col_og: file_num
    name_cols:
    - name_raw
    name_cols_og:
    - name_raw
    table_name: presidents
    table_name_path: data/corp_presidents_clnd.parquet
  - address_cols: []
    address_cols_og: []
    id_col: file_num
    id_col_og: file_num
    name_cols:
    - name_raw
    name_cols_og:
    - name_raw
    table_name: master
    table_name_path: data/corp_master_clnd.parquet
- schema_name: parcel
  tables:
  - address_cols:
    - mailing_address
    - property_address
    address_cols_og:
    - mailing_address
    - property_address
    id_col: pin
    id_col_og: pin
    name_cols:
    - tax_payer_name
    name_cols_og:
    - tax_payer_name
    table_name: parcel
    table_name_path: data/parcel-addresses-foia-24-0230.parquet
