options:
  bad_address_path: data/bad_addresses.csv
  export_tables: false # bool whether to export the tables to csv files
  overwrite_db: true # whether to force overwrite the existing database or add to existing tables
  link_exclusions: 
  update_config_only: false # whether to update the config only
schemas:
  - schema_name: parcel # name of the schema
    tables:
      - address_cols:
          - mailing_address # address column
          - property_address # address column
        id_col: pin # id column
        name_cols:
          - tax_payer_name # name column
        table_name: parcel # name of the table
        table_name_path: data/sample_parcel-addresses-foia-24-0230.parquet # path to the table
metadata:
  existing_links:
  last_updated: # date of the last update
